---
- name: Create a shared dir
  file: path=/mnt/nfs/share state=directory mode=777 owner=root group=root

- name: Ensure NFS utilities are installed.
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - nfs-common
    - nfs-kernel-server

- name: configure /etc/fstab on clients
  action: mount name=/mnt/nfs/share src={{ nfs_server }}:/share fstype=nfs state=mounted
